From python:latest

LABEL MAINTAINER="socialmedia theSam"

ADD . /logs
WORKDIR /logs

# Installing steps

RUN pip install --upgrade pip setuptools wheel
RUN pip install --trusted-host pypi.python.org -r requirements.txt
ENV DJANGO_ENV=development

